### PR TITLE
Added CNContact, Reminders, Calendars, and also iOS 10 UNUserNotificationCenter

### PR DESCRIPTION
**Pull request by akac**
I've also moved the images to their own asset files.

### CODE REVIEW

**Comment by pascalbros** [comment]
Have you tested it successfully?
Obviously this is not compatible with iOS7, right?

Anyway I can merge it into Swift3 branch and when iOS10 will be out, we can just deprecate the master branch into a new one called "legacy" and maintain only the new one.

Makes sense to you?

Cheers

**Comment by akac** [comment]
I have tested it successfully on iOS 10. To be fair, I am iOS 10 only, so iOS 7 doesn't concern me. I understand it does for you, which is why I wrote the code to be supported on iOS 7, 8, and 9 though I did not test on those OSes.

iSO 10 is out now - so is Xcode final - its on the App Store right this moment.

I saw that your Contacts permissions class you mixed old and new style in one class. I used to do that, but recently started just using different classes and instantiating the one I need when the API is so vastly different. The reason is jetissoning the old class is easier than removing line by line the old code.

**Comment by akac** [comment]
I've also got more pushes coming - you can keep or throw them out. They are to be more Swift3 like, and also to get the NS*UsageDescription

**Comment by pascalbros** [comment]
Just merged into Swift3 branch.
I'm downloading Xcode 8.0, I let you know.

Thanks for your contribution.

**Pull request merged**
